### ISSUE TITLE
pandasの基礎.ipynb レビュー

### ISSUE THREAD

**Issue by iktakahiro** [terapyon/leaning-pandas#1]
## データフレームのインデックス

```
df = pd.DataFrame(np.arange(100).reshape(25, 4), columns=list("abcd"))
```

> 上記の `loc` と `iloc` は同じように動作しているが、これは、インデックスの値とインデックス番号同じであるためにこのようになっている

注記があるためお気づきと思いますが、データフレームのインデックス指定を自動採番に任せている例ですが、この場合インデックスラベルとPython のリスト的なインデックスが一致してしまうため、どちらを利用しているか初心者にとってわかりにくいかなと思います。

ただ、25行のダミーのインデックスを作るのは i = ['r1', 'r2', 'r3'....] 冗長なのでその点は悩みどころですね...

## データフレームの内容

```
np.random.rand(25, 4)
```

などとしていますが、無理に 25行つくらなくてももう少しコンパクト行列でいいのでは？と思いました。行数が減ると、上述のダミーのインデックスラベルも作りやすいかな...

## 乱数

ランダム生成の値が毎回変わらなくなるので seed の固定をするとよいですね。

```python
np.random.seed(0)
np.random.rand(25, 4)
```

## 欠損値

欠損値の埋めの話だと、Interpolate (補間）について、紹介だけでも出しておくといいかも知れません。

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html

## コピー

deep/shallow copy について触れるのであれば、データフレームの inplace について触れてもよいと思います。

```
df.sort_values(by='mean', ascending=False, inplace=True)
```

inplace の善し悪しにについて、冪統制が低くなるというか、Notebook をさかのぼって上位の df にも影響を与えているので、わかりにくくなるという意見を目に見にしますね。(df = df... で上書きするなら inplace でも同じですが)

## typo など

> ascending(アセンでヒング）=False　を指定

アセンディング

> a列が0.5以上に絞り込んで、a列の大きい順に並べ替える

a 列が 0.5 以上の行に絞り込んで

> a列が0.5以下に絞り込んで

a 列が 0.5 以下の行に絞り込んで

**Comment by terapyon** [comment]
「インデックス」、「データフレームの内容」、「乱数のseed」は説明が複雑になるので、割愛します。

**Comment by terapyon** [comment]
「欠損値の補間」は説明のみ追記し、typoは修正する。

**Comment by terapyon** [comment]
inplaceコピーは悩むところですが、今回は割愛します。
