### ISSUE TITLE
pandasの外部データ.ipynb レビュー

### ISSUE THREAD

**Issue by iktakahiro** [terapyon/leaning-pandas#2]
# 日付カラム

> df['日付'].astype(np.datetime64)

としていますが、データ読み込み時に指定したほうがよいです。（確認のため、1度未指定のまま読み込んでから再度読み込み直すというのが流れとしては丁寧）

あと、日付がユニークですのでインデックスに指定するのがよいかと。そうすると時系列データとしても扱い易くなるので

```
df = pd.read_csv("201704health.csv", index_col='日付', parse_dates=True)
```

```
# 2週間ごとの集計
df.resample('2W-SUN').mean()

# 月単位の集計（4月しかないので意味ないけど）
df.resample('M').mean()
```

![2017-05-15 22 11 53](https://cloud.githubusercontent.com/assets/1491856/26059123/87bb25c8-39bb-11e7-8356-739c9a49cbca.png)

Weather データのほうも、日付がユニークなので日付をインデックスにしてほしいなぁ。週間平均気温とか簡単に出せるし。（余力があったらサンプルコードを出す）

**Comment by iktakahiro** [comment]
とおして見ました。Slack にノートブックファイルと HTML アップします。

## 要点

### 日付のカラム

Slack でも議論のあったように、日付データをどう取り扱うかはお任せしますが、df.set_index('date') でインデックスにしてしまうとのちのちの結合などが楽になります

天気データについても同様で、datetime 型への変換後にインデックスにしてしまうのがよいと思いました。（手順は Notebook ファイル参照）

### 結合

インデックス同士の結合の場合、concat が使え、*OUTER_JOIN* として振る舞うので便利と思います。

![2017-05-15 23 01 51](https://cloud.githubusercontent.com/assets/1491856/26061339/9cc74580-39c2-11e7-9cb2-47f66c1216d2.png)

### fillna

最後に歩数およびカロリーを zero_fill しています。Notebook のほうには mean() のほうが適当ではないかと書きましたが、データが無いことを示すのであれば 0 でよいと思いました。

**Comment by takanory** [comment]
* 「します」「します。」「しました。」が混ざっているので統一して欲しい
* `df_health = df` はなんのためにやっているのだろう?
* この資料しかみせないんだっけ?「カラムの 0, 6, 7, 8 が順に、「日」「平均気温」「最高気温」「最低気温」となっていましたので、新たなデータフレーム df_weather を、必要なカラムだけにして生成します。」となっているのであれば、本のWebページのキャプチャがほしい

**Comment by terapyon** [comment]
この資料は見せ無いことになりました。
文章は、プロンプター用の原稿になるので、その場の雰囲気で読み替えるか、原稿を作った際に変更を行います。
あくまでも下書きです。

Notebookも別のところから配布するつもりです。

**Comment by terapyon** [comment]
日付をインデックスにし、内容を変更します。
