### ISSUE TITLE
maptlotlib のバージョンが古い

### ISSUE THREAD

**Issue by iktakahiro** [terapyon/leaning-pandas#3]
問題ではないですが、pandas からプロットされている図が matpltolib 1.5版のもののようです。（最新は 2.0.1）

2系のデフォルトスタイル↓

![2017-05-17 23 34 08](https://cloud.githubusercontent.com/assets/1491856/26159390/71e143a0-3b59-11e7-8a47-4b84c4f6f805.png)

**Comment by terapyon** [comment]
手元の環境が古かったので、バージョンアップしました。
指摘ありがとうございました。
