### ISSUE TITLE
スクレイピングのレビュー

### ISSUE THREAD

**Issue by takanory** [terapyon/leaning-pandas#5]
* https://github.com/terapyon/leaning-pandas/blob/master/%E3%82%B9%E3%82%AF%E3%83%AC%E3%82%A4%E3%83%94%E3%83%B3%E3%82%B0.ipynb
* レビューする

**Comment by takanory** [comment]
* import の前に pip install とかはどこでする?
* 習得が成功しました。→取得
* res.content 長いので res.content[:100] とかしてほしい
* bからはじまるので、よりは type(res.content) とかの方が好み
* 人つづ→一つずつ
* 最初は .select() で取得して、つぎはfind(class_='xxx') としているので、どっちかに統一の方がよいのでは?

```python
result = []
for elm in soup.select(".crsItem"):
    title = elm.find(class_="crsTtl")
    hours = elm.find(class_='crsName')
    status = elm.find(class_='crsDate')
    if title is not None and hours is not None and status is not None:
        result.append({'title': title.get_text(), "hours": hours.get_text(), "status": status.get_text()})
```

* ↑先に .get_text() しちゃって try/except でやりたい感もある
* `result.append({'title': title.get_text(), "hours": hours.get_text(), "status": status.get_text()})` 1行が長いので改行して欲しいかな
* `\u3000` 気になるので消したい
* `標準学習時間：10時間` を 10だけにして int にしたい感
* `チュータ： なし　　開講中` も2つにわけて tutor: True/False、status: 開講中とかできるとかっこいい

**Comment by takanory** [comment]
@terapyon よろ

**Comment by terapyon** [comment]
- pip は、その前の節で環境の話をスライドベースでします。
- .select() で取得して、つぎはfind(class_='xxx') → find_all に変更するかも

**Comment by terapyon** [comment]
typoは直します。

**Comment by terapyon** [comment]
他は、修正しないかも。
時間があれば、何か検討します。
