### ISSUE TITLE
matplotlibのレビュー

### ISSUE THREAD

**Issue by takanory** [terapyon/leaning-pandas#6]
* https://github.com/terapyon/leaning-pandas/blob/master/matplotlib%E6%9C%AC%E7%95%AA%E7%94%A8.ipynb

**Comment by takanory** [comment]
* フォントをキャッシュファイルが存在する場合があり→フォントのキャッシュファイル
* 使用しましす。→使用します。
* 環境に合わせて、日本語が表示できるフォントを設定します。→もうちょっと詳しい説明した方がいいかも。もしくは外部の文書を紹介するとか。
  * フォントをインストールします。macOSだと...Windowsだと...みたいな
* 上記のNumPyで作った配列を、NumPyのsin関数に渡すと、サインカーブになった配列が出力されます。→日本語を見直して欲しい。それぞれの値をラジアンとして渡してsinの結果を返している。みたいな
* df_2017.plot()→歩数、カロリーに対して他の値(気温)が低すぎるのでグラフが面白くない
* 円グラフがいまいち。10000歩以上の日数、8000歩~10000歩とかの方が面白そう。ただ、ヒストグラムと同じ感じになる

**Comment by takanory** [comment]
最後に bokeh とか別のグラフ描画ライブラリの紹介があるといいかも

**Comment by terapyon** [comment]
ある程度反映してい、撮影が終わったので、完了とします。
