### ISSUE TITLE
Reveiew: 演習3(気象データ).ipynb

### ISSUE THREAD

**Issue by iktakahiro** [terapyon/leaning-pandas#7]
（元のデータが綺麗でないことが関係しているけど）なにをやっているかよくわからないので、カラム名を指定できるといいかなーと思ったけど、（つまりカラムのラベルに 気圧、や降水量、最低気温、などを与える）綺麗にセットできないようであればこのままでもいいかなと思います。

**Comment by terapyon** [comment]
そこまで、ビデオの中でも説明していません。
データがHTMLテーブルの形が汚いので、きれいにする部分だけで説明が長くなると思い、外しています。

きれいにセットするのは難しいので無しで行きます。
