### ISSUE TITLE
Jupyter Notebook見てみた

### ISSUE THREAD

**Issue by takanory** [terapyon/leaning-pandas#9]
[leaning-pandas/演習1(JupyterNotebook).ipynb at master · terapyon/leaning-pandas](https://github.com/terapyon/leaning-pandas/blob/master/%E6%BC%94%E7%BF%92/%E6%BC%94%E7%BF%921(JupyterNotebook).ipynb "leaning-pandas/演習1(JupyterNotebook).ipynb at master · terapyon/leaning-pandas")

* `5 -2` -> `5 - 2`

[leaning-pandas/演習2(データフレームの扱い).ipynb at master · terapyon/leaning-pandas](https://github.com/terapyon/leaning-pandas/blob/master/%E6%BC%94%E7%BF%92/%E6%BC%94%E7%BF%922(%E3%83%87%E3%83%BC%E3%82%BF%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%81%AE%E6%89%B1%E3%81%84).ipynb "leaning-pandas/演習2(データフレームの扱い).ipynb at master · terapyon/leaning-pandas")

* `上記のデータフレームの値を1行目に1から4、2行目に5から８、３行目に９から１２を入れる` 全角数字と半角数字が混ざってる

[leaning-pandas/演習3(気象データ).ipynb at master · terapyon/leaning-pandas](https://github.com/terapyon/leaning-pandas/blob/master/%E6%BC%94%E7%BF%92/%E6%BC%94%E7%BF%923(%E6%B0%97%E8%B1%A1%E3%83%87%E3%83%BC%E3%82%BF).ipynb "leaning-pandas/演習3(気象データ).ipynb at master · terapyon/leaning-pandas")

* なにをやっているかの手順が、最初に箇条書きで書いてあるとうれしい

[leaning-pandas/演習4(可視化).ipynb at master · terapyon/leaning-pandas](https://github.com/terapyon/leaning-pandas/blob/master/%E6%BC%94%E7%BF%92/%E6%BC%94%E7%BF%924(%E5%8F%AF%E8%A6%96%E5%8C%96).ipynb "leaning-pandas/演習4(可視化).ipynb at master · terapyon/leaning-pandas")

* これってなんで `df_min.head()` の結果で `date` って入っている最低気温に値のない行があるんですか?私がわかってないだけ?

**Comment by terapyon** [comment]
演習4の質問について回答します。

dateをインデックスの名前にしたためです。インデックスのラベルを表示している行です。
pandasの表示上こうなります。最新のNotebookの表示だと違和感がないと思います。
![2017-05-31 10 25 13](https://cloud.githubusercontent.com/assets/485372/26611782/7d425d8c-45eb-11e7-89bb-e150ab854bdb.png)

(言葉で説明するのが難しい・・・)
